/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EmailStatus = { 'Queued' : null } |
  { 'Failed' : null } |
  { 'Sent' : null };
export interface ThesisRequest {
  'email' : string,
  'comment' : [] | [string],
  'timestamp' : bigint,
  'emailStatus' : EmailStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAdminAccess' : ActorMethod<[], { 'ok' : boolean } | { 'err' : string }>,
  'getAccessRequests' : ActorMethod<
    [],
    { 'ok' : Array<ThesisRequest> } |
      { 'err' : string }
  >,
  'getAnalytics' : ActorMethod<
    [],
    {
        'ok' : {
          'visitCount' : bigint,
          'clickCounts' : Array<[string, bigint]>,
        }
      } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterId' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestThesisAccess' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'trackClick' : ActorMethod<[string], undefined>,
  'trackVisit' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];