/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EmailStatus = { 'Queued' : null } |
  { 'Failed' : null } |
  { 'Sent' : null };
export interface ThesisRequest {
  'email' : string,
  'comment' : [] | [string],
  'timestamp' : bigint,
  'emailStatus' : EmailStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Check whether the calling principal is an admin.
   * / Returns #ok(true) if authorized, #err("NotAuthorized") otherwise.
   */
  'checkAdminAccess' : ActorMethod<[], { 'ok' : boolean } | { 'err' : string }>,
  /**
   * / Return all access requests — admin use only.
   * / Non-admin callers receive a #NotAuthorized error.
   */
  'getAccessRequests' : ActorMethod<
    [],
    { 'ok' : Array<ThesisRequest> } |
      { 'err' : string }
  >,
  /**
   * / Return visit and click analytics — admin only.
   */
  'getAnalytics' : ActorMethod<
    [],
    {
        'ok' : {
          'visitCount' : bigint,
          'clickCounts' : Array<[string, bigint]>,
        }
      } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the canister's own principal ID as text. No auth required.
   */
  'getCanisterId' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Submit a thesis access request and trigger the 3-email drip sequence.
   * / Returns #ok("Request received") on success or #err(reason) on validation failure.
   */
  'requestThesisAccess' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Increment the click counter for a given element ID. No auth required.
   */
  'trackClick' : ActorMethod<[string], undefined>,
  /**
   * / Increment the global visit counter. No auth required.
   */
  'trackVisit' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];