/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmailStatus = IDL.Variant({
  'Queued' : IDL.Null,
  'Failed' : IDL.Null,
  'Sent' : IDL.Null,
});
export const ThesisRequest = IDL.Record({
  'email' : IDL.Text,
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'emailStatus' : EmailStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAdminAccess' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      ['query'],
    ),
  'getAccessRequests' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(ThesisRequest), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'visitCount' : IDL.Nat,
            'clickCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestThesisAccess' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'trackClick' : IDL.Func([IDL.Text], [], []),
  'trackVisit' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmailStatus = IDL.Variant({
    'Queued' : IDL.Null,
    'Failed' : IDL.Null,
    'Sent' : IDL.Null,
  });
  const ThesisRequest = IDL.Record({
    'email' : IDL.Text,
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'emailStatus' : EmailStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAdminAccess' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        ['query'],
      ),
    'getAccessRequests' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(ThesisRequest), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'visitCount' : IDL.Nat,
              'clickCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestThesisAccess' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'trackClick' : IDL.Func([IDL.Text], [], []),
    'trackVisit' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };